import './globals.css'
import { Inter, Recursive } from 'next/font/google'
import ThemeProvider from '@/components/ThemeProvider';

const inter = Inter({ subsets: ['latin'] })
const recursive = Recursive({ subsets: ['latin'] })

import '@/canvas'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        {/* @ts-expect-error Server Component */}
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
